services:
  app:
    image: ghcr.io/aleksey925/alert-manager:latest
    restart: on-failure:10
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8080:8080"
    command: serve --host 0.0.0.0 --port 8080

  redis:
    image: redis:6.2.12-alpine
    ports:
      - "6379:6379"
    command: redis-server
